[[permission]]
identifier = "allow-all"
description = "Allows all custom commands in the main crate"
commands.allow = [
  "read_file",
  "read_file_as_base64",
  "save_file",
  "save_file_from_base64",
  "copy_file",
  "list_dir",
  "is_directory",
  "path_exists",
  "create_file",
  "create_dir",
  "open_terminal",
  "reveal_in_explorer",
  "rename_item",
  "delete_item",
  "create_terminal",
  "write_to_terminal",
  "resize_terminal",
  "close_terminal"
]
